name: Publish kafka-ui
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: Docker image name
        required: true
        default: kafka-ui
      image_version:
        description: Docker image version
        required: true
        default: latest
        type: choice
        options:
          - latest
          - 0.4
      image_variant:
        description: Docker image variant
        required: true
        default: all
        type: choice
        options:
          - all
          - alpine
          - debian
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: ${{ inputs.image_variant != 'all' }}
        name: "Build and push - ${{ inputs.image_name }}:${{ inputs.image_version }}-${{ inputs.image_variant }}"
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.image_name }}
          file: ${{ inputs.image_name }}/Dockerfile-${{ inputs.image_version }}_${{ inputs.image_variant }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_version }}-${{ inputs.image_variant }}
      - if: ${{ inputs.image_variant == 'all' }}
        name: "Build and push - ${{ inputs.image_name }}:${{ inputs.image_version }}-alpine"
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.image_name }}
          file: ${{ inputs.image_name }}/Dockerfile-${{ inputs.image_version }}_alpine
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_version }}-alpine
      - if: ${{ inputs.image_variant == 'all' }}
        name: "Build and push - ${{ inputs.image_name }}:${{ inputs.image_version }}-debian"
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.image_name }}
          file: ${{ inputs.image_name }}/Dockerfile-${{ inputs.image_version }}_debian
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_version }}-debian

